# Generated by Django 5.2.6 on 2025-10-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('raion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_addresses', to='aa.raions')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('mask', models.CharField(max_length=15)),
                ('gw', models.GenericIPAddressField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_devices', to='aa.addresses')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_devices', to='aa.types')),
            ],
        ),
    ]
