# Generated by Django 5.2.6 on 2025-10-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_addr', to='aa.addresses'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_type', to='aa.types'),
        ),
    ]
