# Generated by Django 5.2.6 on 2025-10-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0002_alter_devices_address_alter_devices_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types',
            old_name='name',
            new_name='type',
        ),
    ]
