# Generated by Django 5.2.6 on 2025-10-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0003_rename_name_types_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='address',
        ),
        migrations.AddField(
            model_name='addresses',
            name='devices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='back_devices', to='aa.devices'),
            preserve_default=False,
        ),
    ]
