# Generated by Django 5.2.6 on 2025-10-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0004_remove_devices_address_addresses_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='raion',
        ),
        migrations.AddField(
            model_name='raions',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='back_addresses', to='aa.addresses'),
            preserve_default=False,
        ),
    ]
