# Generated by Django 5.2.6 on 2025-10-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0005_remove_addresses_raion_raions_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='raions',
            name='address',
        ),
        migrations.AddField(
            model_name='addresses',
            name='raion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='back_addresses', to='aa.raions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devices',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='back_addr', to='aa.addresses'),
            preserve_default=False,
        ),
    ]
