# Generated by Django 5.2.7 on 2025-10-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0007_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_device', to='aa.addresses'),
        ),
    ]
