# Generated by Django 5.2.7 on 2025-10-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0008_alter_devices_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
